name: Dependabot auto-merge
on:
  pull_request:
permissions:
  contents: write
  pull-requests: write
jobs:
  automerge:
    uses: museumwithnofrontiers/viewer-workflows/.github/workflows/dependabot-automerge.yml@v1.7.1
